name: 'dca crypto job'

on:
  schedule:
    - cron: '0 12 */1 * *' # At 12:00 UTC every day

jobs:
  buy-crypto:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: '14'
      - run: npm install
      - run: npm run purchase
